spring:
  application:
    name: config-server
  cloud:
    config:
      enabled: false 
      server:
        git:
          uri: https://github.com/snowberry200/e-commerce.git
          default-label: master 

server:
  port: 8888
